Import('env')
Import('target_path')

server = env.Program(target_path + 'server', [Glob('*.cpp'), Glob('../game/*.cpp'), Glob('../networking/*.cpp'), Glob('../../ecs/*.cpp'), Glob('../game/commands/*.cpp'), Glob('../game/components/*.cpp')])
#libserver = env.StaticLibrary(target_path + '/test/libserver', [Glob('*.cpp'), Glob('../game/*.cpp')])
#tests = env.BoostTests(Glob("../tests/server/*.cpp"), libserver)