Import('env')
Import('target_path')

server = env.Program(target_path + 'server', Glob('*.cpp'))
libserver = env.StaticLibrary(target_path + '/test/libserver', Glob('*.cpp'))
tests = env.BoostTests(Glob("../tests/server/*.cpp"), libserver)